//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace StockIt_Logica.WSStockIt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSISoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceSI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback asignarPasswordTemporalOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarUsuarioByCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarCategoriasByIdUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarCategoriasActivasByIdUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarClientesByIdUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarClientesActivosByIdUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarProveedoresByIdUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarProveedoresActivosByIdUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceSI() {
            this.Url = global::StockIt_Logica.Properties.Settings.Default.StockIt_Logica_WSStockIt_WebServiceSI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event insertarUsuarioCompletedEventHandler insertarUsuarioCompleted;
        
        /// <remarks/>
        public event actualizarPasswordCompletedEventHandler actualizarPasswordCompleted;
        
        /// <remarks/>
        public event asignarPasswordTemporalCompletedEventHandler asignarPasswordTemporalCompleted;
        
        /// <remarks/>
        public event seleccionarUsuarioByCorreoCompletedEventHandler seleccionarUsuarioByCorreoCompleted;
        
        /// <remarks/>
        public event insertarCategoriaCompletedEventHandler insertarCategoriaCompleted;
        
        /// <remarks/>
        public event actualizarCategoriaCompletedEventHandler actualizarCategoriaCompleted;
        
        /// <remarks/>
        public event eliminarCategoriaCompletedEventHandler eliminarCategoriaCompleted;
        
        /// <remarks/>
        public event seleccionarCategoriasByIdUsuarioCompletedEventHandler seleccionarCategoriasByIdUsuarioCompleted;
        
        /// <remarks/>
        public event seleccionarCategoriasActivasByIdUsuarioCompletedEventHandler seleccionarCategoriasActivasByIdUsuarioCompleted;
        
        /// <remarks/>
        public event insertarClienteCompletedEventHandler insertarClienteCompleted;
        
        /// <remarks/>
        public event actualizarClienteCompletedEventHandler actualizarClienteCompleted;
        
        /// <remarks/>
        public event eliminarClienteCompletedEventHandler eliminarClienteCompleted;
        
        /// <remarks/>
        public event seleccionarClientesByIdUsuarioCompletedEventHandler seleccionarClientesByIdUsuarioCompleted;
        
        /// <remarks/>
        public event seleccionarClientesActivosByIdUsuarioCompletedEventHandler seleccionarClientesActivosByIdUsuarioCompleted;
        
        /// <remarks/>
        public event insertarProveedorCompletedEventHandler insertarProveedorCompleted;
        
        /// <remarks/>
        public event actualizarProveedorCompletedEventHandler actualizarProveedorCompleted;
        
        /// <remarks/>
        public event eliminarProveedorCompletedEventHandler eliminarProveedorCompleted;
        
        /// <remarks/>
        public event seleccionarProveedoresByIdUsuarioCompletedEventHandler seleccionarProveedoresByIdUsuarioCompleted;
        
        /// <remarks/>
        public event seleccionarProveedoresActivosByIdUsuarioCompletedEventHandler seleccionarProveedoresActivosByIdUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int login(string correo, string password) {
            object[] results = this.Invoke("login", new object[] {
                        correo,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string correo, string password) {
            this.loginAsync(correo, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string correo, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        correo,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertarUsuario(string usuario, string nombre, string apellido, string nombrEmpresa, string correo, string password) {
            object[] results = this.Invoke("insertarUsuario", new object[] {
                        usuario,
                        nombre,
                        apellido,
                        nombrEmpresa,
                        correo,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertarUsuarioAsync(string usuario, string nombre, string apellido, string nombrEmpresa, string correo, string password) {
            this.insertarUsuarioAsync(usuario, nombre, apellido, nombrEmpresa, correo, password, null);
        }
        
        /// <remarks/>
        public void insertarUsuarioAsync(string usuario, string nombre, string apellido, string nombrEmpresa, string correo, string password, object userState) {
            if ((this.insertarUsuarioOperationCompleted == null)) {
                this.insertarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarUsuarioOperationCompleted);
            }
            this.InvokeAsync("insertarUsuario", new object[] {
                        usuario,
                        nombre,
                        apellido,
                        nombrEmpresa,
                        correo,
                        password}, this.insertarUsuarioOperationCompleted, userState);
        }
        
        private void OninsertarUsuarioOperationCompleted(object arg) {
            if ((this.insertarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarUsuarioCompleted(this, new insertarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int actualizarPassword(string correo, string passwordAntigua, string passwordNueva) {
            object[] results = this.Invoke("actualizarPassword", new object[] {
                        correo,
                        passwordAntigua,
                        passwordNueva});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarPasswordAsync(string correo, string passwordAntigua, string passwordNueva) {
            this.actualizarPasswordAsync(correo, passwordAntigua, passwordNueva, null);
        }
        
        /// <remarks/>
        public void actualizarPasswordAsync(string correo, string passwordAntigua, string passwordNueva, object userState) {
            if ((this.actualizarPasswordOperationCompleted == null)) {
                this.actualizarPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarPasswordOperationCompleted);
            }
            this.InvokeAsync("actualizarPassword", new object[] {
                        correo,
                        passwordAntigua,
                        passwordNueva}, this.actualizarPasswordOperationCompleted, userState);
        }
        
        private void OnactualizarPasswordOperationCompleted(object arg) {
            if ((this.actualizarPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarPasswordCompleted(this, new actualizarPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/asignarPasswordTemporal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string asignarPasswordTemporal(string correo) {
            object[] results = this.Invoke("asignarPasswordTemporal", new object[] {
                        correo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void asignarPasswordTemporalAsync(string correo) {
            this.asignarPasswordTemporalAsync(correo, null);
        }
        
        /// <remarks/>
        public void asignarPasswordTemporalAsync(string correo, object userState) {
            if ((this.asignarPasswordTemporalOperationCompleted == null)) {
                this.asignarPasswordTemporalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnasignarPasswordTemporalOperationCompleted);
            }
            this.InvokeAsync("asignarPasswordTemporal", new object[] {
                        correo}, this.asignarPasswordTemporalOperationCompleted, userState);
        }
        
        private void OnasignarPasswordTemporalOperationCompleted(object arg) {
            if ((this.asignarPasswordTemporalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.asignarPasswordTemporalCompleted(this, new asignarPasswordTemporalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarUsuarioByCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarUsuarioByCorreo(string correo) {
            object[] results = this.Invoke("seleccionarUsuarioByCorreo", new object[] {
                        correo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarUsuarioByCorreoAsync(string correo) {
            this.seleccionarUsuarioByCorreoAsync(correo, null);
        }
        
        /// <remarks/>
        public void seleccionarUsuarioByCorreoAsync(string correo, object userState) {
            if ((this.seleccionarUsuarioByCorreoOperationCompleted == null)) {
                this.seleccionarUsuarioByCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarUsuarioByCorreoOperationCompleted);
            }
            this.InvokeAsync("seleccionarUsuarioByCorreo", new object[] {
                        correo}, this.seleccionarUsuarioByCorreoOperationCompleted, userState);
        }
        
        private void OnseleccionarUsuarioByCorreoOperationCompleted(object arg) {
            if ((this.seleccionarUsuarioByCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarUsuarioByCorreoCompleted(this, new seleccionarUsuarioByCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertarCategoria(int idUsuario, string nombreCategoria) {
            object[] results = this.Invoke("insertarCategoria", new object[] {
                        idUsuario,
                        nombreCategoria});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertarCategoriaAsync(int idUsuario, string nombreCategoria) {
            this.insertarCategoriaAsync(idUsuario, nombreCategoria, null);
        }
        
        /// <remarks/>
        public void insertarCategoriaAsync(int idUsuario, string nombreCategoria, object userState) {
            if ((this.insertarCategoriaOperationCompleted == null)) {
                this.insertarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarCategoriaOperationCompleted);
            }
            this.InvokeAsync("insertarCategoria", new object[] {
                        idUsuario,
                        nombreCategoria}, this.insertarCategoriaOperationCompleted, userState);
        }
        
        private void OninsertarCategoriaOperationCompleted(object arg) {
            if ((this.insertarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarCategoriaCompleted(this, new insertarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int actualizarCategoria(int idUsuario, int idCategoria, string nombreCategoria) {
            object[] results = this.Invoke("actualizarCategoria", new object[] {
                        idUsuario,
                        idCategoria,
                        nombreCategoria});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarCategoriaAsync(int idUsuario, int idCategoria, string nombreCategoria) {
            this.actualizarCategoriaAsync(idUsuario, idCategoria, nombreCategoria, null);
        }
        
        /// <remarks/>
        public void actualizarCategoriaAsync(int idUsuario, int idCategoria, string nombreCategoria, object userState) {
            if ((this.actualizarCategoriaOperationCompleted == null)) {
                this.actualizarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarCategoriaOperationCompleted);
            }
            this.InvokeAsync("actualizarCategoria", new object[] {
                        idUsuario,
                        idCategoria,
                        nombreCategoria}, this.actualizarCategoriaOperationCompleted, userState);
        }
        
        private void OnactualizarCategoriaOperationCompleted(object arg) {
            if ((this.actualizarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarCategoriaCompleted(this, new actualizarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int eliminarCategoria(int idCategoria) {
            object[] results = this.Invoke("eliminarCategoria", new object[] {
                        idCategoria});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarCategoriaAsync(int idCategoria) {
            this.eliminarCategoriaAsync(idCategoria, null);
        }
        
        /// <remarks/>
        public void eliminarCategoriaAsync(int idCategoria, object userState) {
            if ((this.eliminarCategoriaOperationCompleted == null)) {
                this.eliminarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarCategoriaOperationCompleted);
            }
            this.InvokeAsync("eliminarCategoria", new object[] {
                        idCategoria}, this.eliminarCategoriaOperationCompleted, userState);
        }
        
        private void OneliminarCategoriaOperationCompleted(object arg) {
            if ((this.eliminarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarCategoriaCompleted(this, new eliminarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarCategoriasByIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarCategoriasByIdUsuario(int idUsuario) {
            object[] results = this.Invoke("seleccionarCategoriasByIdUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarCategoriasByIdUsuarioAsync(int idUsuario) {
            this.seleccionarCategoriasByIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void seleccionarCategoriasByIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.seleccionarCategoriasByIdUsuarioOperationCompleted == null)) {
                this.seleccionarCategoriasByIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarCategoriasByIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("seleccionarCategoriasByIdUsuario", new object[] {
                        idUsuario}, this.seleccionarCategoriasByIdUsuarioOperationCompleted, userState);
        }
        
        private void OnseleccionarCategoriasByIdUsuarioOperationCompleted(object arg) {
            if ((this.seleccionarCategoriasByIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarCategoriasByIdUsuarioCompleted(this, new seleccionarCategoriasByIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarCategoriasActivasByIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarCategoriasActivasByIdUsuario(int idUsuario) {
            object[] results = this.Invoke("seleccionarCategoriasActivasByIdUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarCategoriasActivasByIdUsuarioAsync(int idUsuario) {
            this.seleccionarCategoriasActivasByIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void seleccionarCategoriasActivasByIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.seleccionarCategoriasActivasByIdUsuarioOperationCompleted == null)) {
                this.seleccionarCategoriasActivasByIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarCategoriasActivasByIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("seleccionarCategoriasActivasByIdUsuario", new object[] {
                        idUsuario}, this.seleccionarCategoriasActivasByIdUsuarioOperationCompleted, userState);
        }
        
        private void OnseleccionarCategoriasActivasByIdUsuarioOperationCompleted(object arg) {
            if ((this.seleccionarCategoriasActivasByIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarCategoriasActivasByIdUsuarioCompleted(this, new seleccionarCategoriasActivasByIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertarCliente(int idUsuario, string nombre, string apellido, string sexo, string telefono, string correo) {
            object[] results = this.Invoke("insertarCliente", new object[] {
                        idUsuario,
                        nombre,
                        apellido,
                        sexo,
                        telefono,
                        correo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertarClienteAsync(int idUsuario, string nombre, string apellido, string sexo, string telefono, string correo) {
            this.insertarClienteAsync(idUsuario, nombre, apellido, sexo, telefono, correo, null);
        }
        
        /// <remarks/>
        public void insertarClienteAsync(int idUsuario, string nombre, string apellido, string sexo, string telefono, string correo, object userState) {
            if ((this.insertarClienteOperationCompleted == null)) {
                this.insertarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarClienteOperationCompleted);
            }
            this.InvokeAsync("insertarCliente", new object[] {
                        idUsuario,
                        nombre,
                        apellido,
                        sexo,
                        telefono,
                        correo}, this.insertarClienteOperationCompleted, userState);
        }
        
        private void OninsertarClienteOperationCompleted(object arg) {
            if ((this.insertarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarClienteCompleted(this, new insertarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int actualizarCliente(int idUsuario, int idCliente, string nombre, string apellido, string sexo, string telefono, string correo) {
            object[] results = this.Invoke("actualizarCliente", new object[] {
                        idUsuario,
                        idCliente,
                        nombre,
                        apellido,
                        sexo,
                        telefono,
                        correo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarClienteAsync(int idUsuario, int idCliente, string nombre, string apellido, string sexo, string telefono, string correo) {
            this.actualizarClienteAsync(idUsuario, idCliente, nombre, apellido, sexo, telefono, correo, null);
        }
        
        /// <remarks/>
        public void actualizarClienteAsync(int idUsuario, int idCliente, string nombre, string apellido, string sexo, string telefono, string correo, object userState) {
            if ((this.actualizarClienteOperationCompleted == null)) {
                this.actualizarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarClienteOperationCompleted);
            }
            this.InvokeAsync("actualizarCliente", new object[] {
                        idUsuario,
                        idCliente,
                        nombre,
                        apellido,
                        sexo,
                        telefono,
                        correo}, this.actualizarClienteOperationCompleted, userState);
        }
        
        private void OnactualizarClienteOperationCompleted(object arg) {
            if ((this.actualizarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarClienteCompleted(this, new actualizarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int eliminarCliente(int idCliente) {
            object[] results = this.Invoke("eliminarCliente", new object[] {
                        idCliente});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarClienteAsync(int idCliente) {
            this.eliminarClienteAsync(idCliente, null);
        }
        
        /// <remarks/>
        public void eliminarClienteAsync(int idCliente, object userState) {
            if ((this.eliminarClienteOperationCompleted == null)) {
                this.eliminarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarClienteOperationCompleted);
            }
            this.InvokeAsync("eliminarCliente", new object[] {
                        idCliente}, this.eliminarClienteOperationCompleted, userState);
        }
        
        private void OneliminarClienteOperationCompleted(object arg) {
            if ((this.eliminarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarClienteCompleted(this, new eliminarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarClientesByIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarClientesByIdUsuario(int idUsuario) {
            object[] results = this.Invoke("seleccionarClientesByIdUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarClientesByIdUsuarioAsync(int idUsuario) {
            this.seleccionarClientesByIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void seleccionarClientesByIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.seleccionarClientesByIdUsuarioOperationCompleted == null)) {
                this.seleccionarClientesByIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarClientesByIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("seleccionarClientesByIdUsuario", new object[] {
                        idUsuario}, this.seleccionarClientesByIdUsuarioOperationCompleted, userState);
        }
        
        private void OnseleccionarClientesByIdUsuarioOperationCompleted(object arg) {
            if ((this.seleccionarClientesByIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarClientesByIdUsuarioCompleted(this, new seleccionarClientesByIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarClientesActivosByIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarClientesActivosByIdUsuario(int idUsuario) {
            object[] results = this.Invoke("seleccionarClientesActivosByIdUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarClientesActivosByIdUsuarioAsync(int idUsuario) {
            this.seleccionarClientesActivosByIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void seleccionarClientesActivosByIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.seleccionarClientesActivosByIdUsuarioOperationCompleted == null)) {
                this.seleccionarClientesActivosByIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarClientesActivosByIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("seleccionarClientesActivosByIdUsuario", new object[] {
                        idUsuario}, this.seleccionarClientesActivosByIdUsuarioOperationCompleted, userState);
        }
        
        private void OnseleccionarClientesActivosByIdUsuarioOperationCompleted(object arg) {
            if ((this.seleccionarClientesActivosByIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarClientesActivosByIdUsuarioCompleted(this, new seleccionarClientesActivosByIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertarProveedor(int idUsuario, string nombre, string telefono, string direccion, string correo) {
            object[] results = this.Invoke("insertarProveedor", new object[] {
                        idUsuario,
                        nombre,
                        telefono,
                        direccion,
                        correo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertarProveedorAsync(int idUsuario, string nombre, string telefono, string direccion, string correo) {
            this.insertarProveedorAsync(idUsuario, nombre, telefono, direccion, correo, null);
        }
        
        /// <remarks/>
        public void insertarProveedorAsync(int idUsuario, string nombre, string telefono, string direccion, string correo, object userState) {
            if ((this.insertarProveedorOperationCompleted == null)) {
                this.insertarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarProveedorOperationCompleted);
            }
            this.InvokeAsync("insertarProveedor", new object[] {
                        idUsuario,
                        nombre,
                        telefono,
                        direccion,
                        correo}, this.insertarProveedorOperationCompleted, userState);
        }
        
        private void OninsertarProveedorOperationCompleted(object arg) {
            if ((this.insertarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarProveedorCompleted(this, new insertarProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int actualizarProveedor(int idUsuario, int idProveedor, string nombre, string telefono, string direccion, string correo) {
            object[] results = this.Invoke("actualizarProveedor", new object[] {
                        idUsuario,
                        idProveedor,
                        nombre,
                        telefono,
                        direccion,
                        correo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarProveedorAsync(int idUsuario, int idProveedor, string nombre, string telefono, string direccion, string correo) {
            this.actualizarProveedorAsync(idUsuario, idProveedor, nombre, telefono, direccion, correo, null);
        }
        
        /// <remarks/>
        public void actualizarProveedorAsync(int idUsuario, int idProveedor, string nombre, string telefono, string direccion, string correo, object userState) {
            if ((this.actualizarProveedorOperationCompleted == null)) {
                this.actualizarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarProveedorOperationCompleted);
            }
            this.InvokeAsync("actualizarProveedor", new object[] {
                        idUsuario,
                        idProveedor,
                        nombre,
                        telefono,
                        direccion,
                        correo}, this.actualizarProveedorOperationCompleted, userState);
        }
        
        private void OnactualizarProveedorOperationCompleted(object arg) {
            if ((this.actualizarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarProveedorCompleted(this, new actualizarProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int eliminarProveedor(int idProveedor) {
            object[] results = this.Invoke("eliminarProveedor", new object[] {
                        idProveedor});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarProveedorAsync(int idProveedor) {
            this.eliminarProveedorAsync(idProveedor, null);
        }
        
        /// <remarks/>
        public void eliminarProveedorAsync(int idProveedor, object userState) {
            if ((this.eliminarProveedorOperationCompleted == null)) {
                this.eliminarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarProveedorOperationCompleted);
            }
            this.InvokeAsync("eliminarProveedor", new object[] {
                        idProveedor}, this.eliminarProveedorOperationCompleted, userState);
        }
        
        private void OneliminarProveedorOperationCompleted(object arg) {
            if ((this.eliminarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarProveedorCompleted(this, new eliminarProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarProveedoresByIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarProveedoresByIdUsuario(int idUsuario) {
            object[] results = this.Invoke("seleccionarProveedoresByIdUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarProveedoresByIdUsuarioAsync(int idUsuario) {
            this.seleccionarProveedoresByIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void seleccionarProveedoresByIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.seleccionarProveedoresByIdUsuarioOperationCompleted == null)) {
                this.seleccionarProveedoresByIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarProveedoresByIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("seleccionarProveedoresByIdUsuario", new object[] {
                        idUsuario}, this.seleccionarProveedoresByIdUsuarioOperationCompleted, userState);
        }
        
        private void OnseleccionarProveedoresByIdUsuarioOperationCompleted(object arg) {
            if ((this.seleccionarProveedoresByIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarProveedoresByIdUsuarioCompleted(this, new seleccionarProveedoresByIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarProveedoresActivosByIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet seleccionarProveedoresActivosByIdUsuario(int idUsuario) {
            object[] results = this.Invoke("seleccionarProveedoresActivosByIdUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarProveedoresActivosByIdUsuarioAsync(int idUsuario) {
            this.seleccionarProveedoresActivosByIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void seleccionarProveedoresActivosByIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.seleccionarProveedoresActivosByIdUsuarioOperationCompleted == null)) {
                this.seleccionarProveedoresActivosByIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarProveedoresActivosByIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("seleccionarProveedoresActivosByIdUsuario", new object[] {
                        idUsuario}, this.seleccionarProveedoresActivosByIdUsuarioOperationCompleted, userState);
        }
        
        private void OnseleccionarProveedoresActivosByIdUsuarioOperationCompleted(object arg) {
            if ((this.seleccionarProveedoresActivosByIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarProveedoresActivosByIdUsuarioCompleted(this, new seleccionarProveedoresActivosByIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertarUsuarioCompletedEventHandler(object sender, insertarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarPasswordCompletedEventHandler(object sender, actualizarPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void asignarPasswordTemporalCompletedEventHandler(object sender, asignarPasswordTemporalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class asignarPasswordTemporalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal asignarPasswordTemporalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarUsuarioByCorreoCompletedEventHandler(object sender, seleccionarUsuarioByCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarUsuarioByCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarUsuarioByCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertarCategoriaCompletedEventHandler(object sender, insertarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarCategoriaCompletedEventHandler(object sender, actualizarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarCategoriaCompletedEventHandler(object sender, eliminarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarCategoriasByIdUsuarioCompletedEventHandler(object sender, seleccionarCategoriasByIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarCategoriasByIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarCategoriasByIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarCategoriasActivasByIdUsuarioCompletedEventHandler(object sender, seleccionarCategoriasActivasByIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarCategoriasActivasByIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarCategoriasActivasByIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertarClienteCompletedEventHandler(object sender, insertarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarClienteCompletedEventHandler(object sender, actualizarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarClienteCompletedEventHandler(object sender, eliminarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarClientesByIdUsuarioCompletedEventHandler(object sender, seleccionarClientesByIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarClientesByIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarClientesByIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarClientesActivosByIdUsuarioCompletedEventHandler(object sender, seleccionarClientesActivosByIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarClientesActivosByIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarClientesActivosByIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertarProveedorCompletedEventHandler(object sender, insertarProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarProveedorCompletedEventHandler(object sender, actualizarProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarProveedorCompletedEventHandler(object sender, eliminarProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarProveedoresByIdUsuarioCompletedEventHandler(object sender, seleccionarProveedoresByIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarProveedoresByIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarProveedoresByIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void seleccionarProveedoresActivosByIdUsuarioCompletedEventHandler(object sender, seleccionarProveedoresActivosByIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarProveedoresActivosByIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarProveedoresActivosByIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591